### ISSUE TITLE
v1 分支的 banks.json 现在还可以用吗？

### ISSUE THREAD

**Issue by TheWaWaR** [ALawating-Rex/AreaAndBanks#1]
据我观察 banks.json 里的数据应该都是从微信爬的。
而且比这个项目里的数据更全： https://github.com/yuche/wechat-banks

废弃的理由是？
现在我还可以用 banks.json 里的数据吗？

**Comment by ALawating-Rex** [comment]
不好意思，才看到。 参考的是这个项目的数据，但是手动修改了很多数据。废弃主要是想把省市区和银行统一起来，我们有个返佣系统，佣金转账银行的，就在用这个数据，个人感觉可以使用目前最新的代码。同时建议如果是用户输入支行，给他能够自己填写支行地址或者反馈新的支行地址的通道。
