### ISSUE TITLE
直接执行SQL报错, 有解决的办法吗?

### ISSUE THREAD

**Issue by liaohui5** [ALawating-Rex/AreaAndBanks#3]
![image](https://user-images.githubusercontent.com/29266093/50579605-7f404800-0e81-11e9-89d6-62cb63b42ef2.png)

**Comment by ALawating-Rex** [comment]
建议通过命令行来执行导入，举例windows下：
方法1.cmd 下
mysql -u root -p --default-character-set=utf8 test <d:\banks.sql
数据库名称 和 用户等根据实际修改

方法2.cmd 下
登录mysql: mysql -uroot -p
指定数据库： use test;
使用source导入: source d:\banks.sql

**Comment by liaohui5** [comment]
已经解决了, 哈哈 @ALawating-Rex

**Comment by liaohui5** [comment]
@ALawating-Rex  navicat 导入数据量过多比如超过 10万条就会失败,不知道为什么
