### ISSUE TITLE
数据不是标准数据，根本没法用

### ISSUE THREAD

**Issue by uszlian** [ALawating-Rex/AreaAndBanks#5]

**Comment by ALawating-Rex** [comment]
你说的哪个数据不是标准数据呢？ 省市区数据来自政府网站， 也附上了获取最新数据的方法。
银行数据我这确实不是标准数据，这里也没说过数据来自官方标准数据。

**Comment by uszlian** [comment]
抱歉。我一开始是想找支行代码和区域的映射来使用的。一直没找到完整的。你这种方式是可以直接用的。
